---
abstract: 'log storage and log readers'
author:
  - 'Vyacheslav Matyukhin <me@berekuk.ru>'
build_requires:
  IPC::System::Simple: 0
  Test::Class: 0
  Test::Fatal: 0
  Test::More: 0
  autodie: 0
  parent: 0
  strict: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300029, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Flux-Log
requires:
  File::Basename: 0
  Flux::File: 0
  Flux::In::Role::Easy: 0
  Flux::In::Role::Lag: 0
  Flux::Role::Description: 0
  Flux::Storage::Role::ClientList: 0
  Log::Unrotate: 0
  Moo: 0
  Type::Library: 0
  Type::Params: 0
  Type::Utils: 0
  Types::Standard: 0
resources:
  bugtracker: https://github.com/berekuk/Flux-Log/issues
  repository: git://github.com/berekuk/Flux-Log.git
version: 1.00
